import { FormEvent, useEffect, useState } from 'react';
import { Building2, LockKeyhole, RefreshCcw, Repeat2, Save, ShieldCheck, SlidersHorizontal, WalletCards } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { supabase } from '../../lib/supabase';
import { formatMoney, formatShortDate } from '../../lib/utils';
import { PageContainer, PageHeader, Card, Button, Spinner, Badge } from '../ui/Shared';

export default function PharmacyOperations() {
  const { business } = useAuth();
  const [branches, setBranches] = useState<any[]>([]);
  const [registers, setRegisters] = useState<any[]>([]);
  const [transfers, setTransfers] = useState<any[]>([]);
  const [roles, setRoles] = useState<any[]>([]);
  const [logs, setLogs] = useState<any[]>([]);
  const [movements, setMovements] = useState<any[]>([]);
  const [medicines, setMedicines] = useState<any[]>([]);
  const [batches, setBatches] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [branch, setBranch] = useState({ name: '', code: '', address: '', phone: '' });
  const [adjust, setAdjust] = useState({ medicine_id: '', batch_id: '', adjustment_type: 'decrease', quantity: '', reason: '' });
  const [transfer, setTransfer] = useState({ from_branch_id: '', to_branch_id: '', medicine_id: '', batch_id: '', quantity: '', note: '' });

  const load = async () => { if (!business) return; setLoading(true); const [br, reg, tr, ro, lo, mv, med, ba] = await Promise.all([supabase.from('branches').select('*').eq('business_id', business.id).order('name', { ascending: true }), supabase.from('cash_registers').select('*').eq('business_id', business.id).order('created_at', { ascending: false }), supabase.from('stock_transfers').select('*').eq('business_id', business.id).order('created_at', { ascending: false }), supabase.from('role_permissions').select('*').eq('business_id', business.id).order('role', { ascending: true }), supabase.from('audit_logs').select('*').eq('business_id', business.id).order('created_at', { ascending: false }).limit(30), supabase.from('stock_movements').select('*').eq('business_id', business.id).order('created_at', { ascending: false }).limit(40), supabase.from('medicines').select('*').eq('business_id', business.id).order('name', { ascending: true }), supabase.from('medicine_batches').select('*').eq('business_id', business.id).order('expiry_date', { ascending: true })]); setBranches(br.data as any[] || []); setRegisters(reg.data as any[] || []); setTransfers(tr.data as any[] || []); setRoles(ro.data as any[] || []); setLogs(lo.data as any[] || []); setMovements(mv.data as any[] || []); setMedicines(med.data as any[] || []); setBatches(ba.data as any[] || []); setLoading(false); };
  useEffect(() => { load(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [business]);
  const addBranch = async (e: FormEvent) => { e.preventDefault(); if (!business) return; await supabase.from('branches').insert({ business_id: business.id, ...branch, is_active: true }); setBranch({ name: '', code: '', address: '', phone: '' }); load(); };
  const openRegister = async () => { if (!business) return; await supabase.from('cash_registers').insert({ business_id: business.id, branch_id: branches[0]?.id || null, opening_cash: 5000, expected_cash: 5000, status: 'open' }); load(); };
  const closeRegister = async (r: any) => { await supabase.from('cash_registers').update({ status: 'closed', closed_at: new Date().toISOString(), closing_cash: r.expected_cash, difference: 0 }).eq('id', r.id); load(); };
  const addAdjustment = async (e: FormEvent) => { e.preventDefault(); if (!business) return; const qty = Number(adjust.quantity || 0); const batch = batches.find((b) => b.id === adjust.batch_id); const next = Math.max(Number(batch?.available_quantity || 0) + (adjust.adjustment_type === 'increase' ? qty : -qty), 0); await supabase.from('stock_adjustments').insert({ business_id: business.id, ...adjust, quantity: qty }); if (batch) await supabase.from('medicine_batches').update({ available_quantity: next, status: ['damaged','expired'].includes(adjust.adjustment_type) ? adjust.adjustment_type : batch.status }).eq('id', batch.id); await supabase.from('stock_movements').insert({ business_id: business.id, branch_id: batch?.branch_id || null, medicine_id: adjust.medicine_id, batch_id: adjust.batch_id, type: adjust.adjustment_type === 'increase' ? 'adjustment' : adjust.adjustment_type === 'damaged' ? 'damage' : adjust.adjustment_type === 'expired' ? 'expiry' : 'adjustment', quantity_in: adjust.adjustment_type === 'increase' ? qty : 0, quantity_out: adjust.adjustment_type === 'increase' ? 0 : qty, balance_after: next, reference: 'Stock adjustment', note: adjust.reason }); setAdjust({ medicine_id: '', batch_id: '', adjustment_type: 'decrease', quantity: '', reason: '' }); load(); };
  const addTransfer = async (e: FormEvent) => { e.preventDefault(); if (!business) return; const qty = Number(transfer.quantity || 0); await supabase.from('stock_transfers').insert({ business_id: business.id, ...transfer, quantity: qty, status: 'sent' }); await supabase.from('stock_movements').insert([{ business_id: business.id, branch_id: transfer.from_branch_id, medicine_id: transfer.medicine_id, batch_id: transfer.batch_id, type: 'transfer_out', quantity_out: qty, quantity_in: 0, balance_after: 0, reference: 'Branch transfer', note: transfer.note }, { business_id: business.id, branch_id: transfer.to_branch_id, medicine_id: transfer.medicine_id, batch_id: transfer.batch_id, type: 'transfer_in', quantity_in: qty, quantity_out: 0, balance_after: qty, reference: 'Branch transfer', note: transfer.note }]); setTransfer({ from_branch_id: '', to_branch_id: '', medicine_id: '', batch_id: '', quantity: '', note: '' }); load(); };
  if (loading) return <Spinner label="Loading pharmacy operations…" />;
  return <PageContainer className="max-w-8xl"><PageHeader title="Operations, Branches, Permissions & Audit Logs" subtitle="Multi-branch transfer, stock adjustments, damaged/expired stock, cash register, role permissions and detailed audit logs." action={<Button onClick={load}><RefreshCcw className="h-4 w-4" />Refresh</Button>} />
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-5 mb-5"><Card className="p-5"><h3 className="font-bold mb-3 flex gap-2"><Building2 className="h-5 w-5 text-emerald-600"/>Add branch</h3><form onSubmit={addBranch} className="space-y-3"><Input label="Name" value={branch.name} onChange={(v) => setBranch({...branch,name:v})} required/><Input label="Code" value={branch.code} onChange={(v) => setBranch({...branch,code:v})}/><Input label="Address" value={branch.address} onChange={(v) => setBranch({...branch,address:v})}/><Input label="Phone" value={branch.phone} onChange={(v) => setBranch({...branch,phone:v})}/><Button type="submit" className="w-full"><Save className="h-4 w-4"/>Save branch</Button></form></Card>
      <Card className="p-5"><h3 className="font-bold mb-3 flex gap-2"><SlidersHorizontal className="h-5 w-5 text-emerald-600"/>Stock adjustment</h3><form onSubmit={addAdjustment} className="space-y-3"><Select label="Medicine" value={adjust.medicine_id} options={medicines.map(m=>({value:m.id,label:m.name}))} onChange={(v)=>setAdjust({...adjust,medicine_id:v})}/><Select label="Batch" value={adjust.batch_id} options={batches.filter(b=>!adjust.medicine_id||b.medicine_id===adjust.medicine_id).map(b=>({value:b.id,label:b.batch_number}))} onChange={(v)=>setAdjust({...adjust,batch_id:v})}/><Select label="Type" value={adjust.adjustment_type} options={['increase','decrease','damaged','expired']} onChange={(v)=>setAdjust({...adjust,adjustment_type:v})}/><Input label="Quantity" type="number" value={adjust.quantity} onChange={(v)=>setAdjust({...adjust,quantity:v})}/><Input label="Reason" value={adjust.reason} onChange={(v)=>setAdjust({...adjust,reason:v})}/><Button type="submit" className="w-full">Save adjustment</Button></form></Card>
      <Card className="p-5"><h3 className="font-bold mb-3 flex gap-2"><Repeat2 className="h-5 w-5 text-emerald-600"/>Branch transfer</h3><form onSubmit={addTransfer} className="space-y-3"><Select label="From" value={transfer.from_branch_id} options={branches.map(b=>({value:b.id,label:b.name}))} onChange={(v)=>setTransfer({...transfer,from_branch_id:v})}/><Select label="To" value={transfer.to_branch_id} options={branches.map(b=>({value:b.id,label:b.name}))} onChange={(v)=>setTransfer({...transfer,to_branch_id:v})}/><Select label="Medicine" value={transfer.medicine_id} options={medicines.map(m=>({value:m.id,label:m.name}))} onChange={(v)=>setTransfer({...transfer,medicine_id:v})}/><Select label="Batch" value={transfer.batch_id} options={batches.filter(b=>!transfer.medicine_id||b.medicine_id===transfer.medicine_id).map(b=>({value:b.id,label:b.batch_number}))} onChange={(v)=>setTransfer({...transfer,batch_id:v})}/><Input label="Quantity" type="number" value={transfer.quantity} onChange={(v)=>setTransfer({...transfer,quantity:v})}/><Input label="Note" value={transfer.note} onChange={(v)=>setTransfer({...transfer,note:v})}/><Button type="submit" className="w-full">Create transfer</Button></form></Card></div>
    <div className="grid grid-cols-1 xl:grid-cols-2 gap-5"><Card className="p-5"><div className="flex justify-between items-center mb-3"><h3 className="font-bold flex gap-2"><WalletCards className="h-5 w-5 text-emerald-600"/>Cash register</h3><Button size="sm" onClick={openRegister}>Open register</Button></div><SimpleTable rows={registers} cols={['status','opening_cash','closing_cash','expected_cash','difference','opened_at']} currency={business?.currency || 'BDT'} moneyCols={['opening_cash','closing_cash','expected_cash','difference']} actions={(r:any)=>r.status==='open'?<Button size="sm" variant="outline" onClick={()=>closeRegister(r)}>Close</Button>:null}/></Card><TableCard title="Branches" rows={branches} cols={['name','code','address','phone','is_active']}/><TableCard title="Stock transfers" rows={transfers} cols={['status','quantity','note','created_at']}/><TableCard title="Role based permissions" rows={roles} cols={['role','permissions','is_active']} icon={<LockKeyhole/>}/><TableCard title="Stock movement ledger" rows={movements} cols={['type','quantity_in','quantity_out','balance_after','reference','created_at']}/><TableCard title="Audit logs" rows={logs} cols={['action','resource','resource_id','created_at']} icon={<ShieldCheck/>}/></div>
  </PageContainer>;
}
function Input({ label, value, onChange, type='text', required }: any) { return <label className="block"><span className="text-xs font-bold text-slate-600">{label}</span><input required={required} type={type} value={value} onChange={(e)=>onChange(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"/></label>; }
function Select({ label, value, onChange, options }: any) { return <label className="block"><span className="text-xs font-bold text-slate-600">{label}</span><select value={value} onChange={(e)=>onChange(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="">Select</option>{options.map((o:any)=>typeof o==='string'?<option key={o} value={o}>{o}</option>:<option key={o.value} value={o.value}>{o.label}</option>)}</select></label>; }
function TableCard({ title, rows, cols, icon }: any) { return <Card className="p-5"><h3 className="font-bold mb-3 flex gap-2 [&>svg]:h-5 [&>svg]:w-5 [&>svg]:text-emerald-600">{icon}{title}</h3><SimpleTable rows={rows} cols={cols}/></Card>; }
function SimpleTable({ rows, cols, currency='BDT', moneyCols=[], actions }: any) { const money=new Set(moneyCols); return <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="text-left text-xs uppercase tracking-wide text-slate-500 border-b">{cols.map((c:string)=><th key={c} className="py-2">{c.replaceAll('_',' ')}</th>)}{actions&&<th/>}</tr></thead><tbody>{rows.map((r:any)=><tr key={r.id} className="border-b border-slate-100">{cols.map((c:string)=><td key={c} className="py-2 max-w-56 truncate">{c.includes('date')||c.endsWith('_at')?(r[c]?formatShortDate(r[c]):'-'):money.has(c)?formatMoney(Number(r[c]||0),currency):c==='status'?<Badge color={r[c]==='open'||r[c]==='sent'?'green':'slate'}>{r[c]}</Badge>:Array.isArray(r[c])?r[c].join(', '):String(r[c]??'-')}</td>)}{actions&&<td>{actions(r)}</td>}</tr>)}{rows.length===0&&<tr><td colSpan={cols.length+1} className="py-8 text-center text-slate-500">No records.</td></tr>}</tbody></table></div>; }
